# Generated by Django 4.2.3 on 2023-09-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='question',
            name='video',
            field=models.URLField(blank=True),
        ),
    ]
