# Generated by Django 4.2.3 on 2023-09-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_explanation_question_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='explanation',
            new_name='explanation_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='video',
            new_name='explanation_video',
        ),
        migrations.AddField(
            model_name='question',
            name='question_diagram',
            field=models.ImageField(blank=True, null=True, upload_to='diagram/'),
        ),
    ]
