# Generated by Django 4.2.3 on 2023-09-03 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Material',
            new_name='Revision',
        ),
    ]
