# Generated by Django 4.2.3 on 2023-09-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.URLField(blank=True, default=''),
        ),
    ]
